import {
  Box,
  Heading,
  Text,
  VStack,
  Button,
  Divider,
  useBreakpointValue,
} from "@chakra-ui/react";
import { useParams, Link as RouterLink } from "react-router-dom";

export default function LessonView() {
  const { courseId, moduleIndex, lessonIndex } = useParams();
  const fontSize = useBreakpointValue({ base: "md", md: "lg" });

  return (
    <Box w="100%">
      <VStack align="start" spacing={5} maxW="100%">
        <Heading fontSize={{ base: "2xl", md: "3xl" }}>
          Lesson {Number(lessonIndex) + 1} — Module {Number(moduleIndex) + 1}
        </Heading>
        <Divider />
        <Text fontSize={fontSize} color="gray.600">
          This is a placeholder lesson. Soon, this will render structured JSON
          content: headings, paragraphs, code, videos, and quizzes — dynamically
          generated by AI.
        </Text>
        <Button
          as={RouterLink}
          to={`/courses/${courseId}/module/${moduleIndex}/lesson/${
            Number(lessonIndex) + 1
          }`}
          colorScheme="blue"
          borderRadius="full"
          size="md"
        >
          Next Lesson →
        </Button>
      </VStack>
    </Box>
  );
}
